### ISSUE TITLE
Payment has to be captured manually (?)

### ISSUE THREAD

**Issue by akselhenriksen79** [PayEx/payex-woocommerce-payments#10]
The order is eventually cancelled from a timeout it appears even though payment has been successfull (using credit card) .  I have to go in an manually click "capture payment" in a payex box which appears above the order notes. 

Then the order is changed from cancelled to Processing.

Isn't there a way to make the payment gateway automatically capture the payment if valid and set the order as completed??

**Comment by sjobidoo** [comment]
Any response to this? We need to change sollution if this is not possible with this plugin :(

**Comment by mikaelengstrom** [comment]
@sjobidoo  – there is a AutoCapture setting in the gateway, it relies on webhooks, so on a staging environment you can not have required enpoints to be behind basic auth.

@aait – You should document theese features somewhere.
