### ISSUE TITLE
Error on payment with new version of plugin

### ISSUE THREAD

**Issue by bomyras** [PayEx/payex-woocommerce-payments#7]
After the new version of the plugin is deployed, we get the following error when the customer is trying to pay:

{"type":"https://api.payex.com/psp/errordetail/vipps/InputError","title":"Bad Request","status":"400","instance":"d3e1f1f0-7ee7-5cb2-bc41-ca1b6f82ab29","detail":"RetryWithNewData","problems":[{"name":"Payment.PrefillInfo.Msisdn","description":"The field Msisdn must match the regular expression '^(\\+47)(?:4[015-8]|5[89]|87|9\\d)\\d{6}$'"}]}

In our store the customer normally inputs his phone number in one of these formats: 987 66 544 or 98 77 66 55 or 99 88 77 66 or 99887766. He never inputs with +47 in front.

**Comment by olegisk** [comment]
Hi @bomyras 
I'm implement wp filter payex_vipps_phone_format() to control phone format.
You can fix problem using this filter.
Open wp-content/themes/{your-theme}/functions.php and add follow lines to end:

```php
add_filter( 'payex_vipps_phone_format', 'payex_vipps_phone_format', 20, 2 );
function payex_vipps_phone_format( $phone, $order ) {
	$phone = str_replace( ' ', '', $phone );
	if (mb_strpos($phone, '+47', 0, 'UTF-8') !== false) {
		return $phone;
	}
	return '+47' . $phone;
}
```

I hope that your problem will be solved :-)
