### ISSUE TITLE
Error if customer cancel payment and tries to pay again

### ISSUE THREAD

**Issue by bomyras** [PayEx/payex-woocommerce-payments#8]
If the customer cancels the payment in the app, and browse "back" in the browser, and then tries to pay again, this error is displayed:

{"type":"https://api.payex.com/psp/errordetail/vipps/InputError","title":"Bad Request","status":"400","instance":"ee9ba284-c938-5a82-a58b-5a9e894b4231","detail":"RetryWithNewData","problems":[{"name":"PayeeReference","description":"The given PayeeReference (7aebb774-5876-57c1-bc39-3cd6cb) has already been used for another payment (12100000126)."}]}

**Comment by olegisk** [comment]
Hi @bomyras 
Which method used? direct or redirect?
