### ISSUE TITLE
Vipps still not working

### ISSUE THREAD

**Issue by saumoor** [PayEx/payex-woocommerce-payments#9]
Vipps plugin still not functional, right now getting this error message no matter what way I try to put in the number: "detail":"RetryWithNewData","problems":[{"name":"PaymentPrefillInfoMsisdn","description":"The field Msisdn must match the regular expression '^(\\+47)(?:4[015-8]|5[89]|87|9\\d)\\d{6}$'"}]}

**Comment by olegisk** [comment]
Hi @saumoor 
Which phone number was entered?

**Comment by olegisk** [comment]
https://github.com/PayEx/PayEx.Psp.WooCommerce/commit/3b5f2a2b5a49528ec349e14e222be9a9c49b7f8f

**Comment by olegisk** [comment]
https://github.com/PayEx/PayEx.Psp.WooCommerce/commit/f8c750d7f9810c0095c369973c4d3a00c6dfa183

**Comment by saumoor** [comment]
Got it to work with putting in +47 before the number. 
Can you update so that the way the number should be input is visible somewhere in the checkout?

**Comment by patrickhrml** [comment]
Is there any update on this issue? As the error message given when not typing +47 is messy code and there's no indication in the checkout form at the Phone parameter that you should enter +47. Is there a way to edit the checkout form to add a text, or could this be added to the plugin?

**Comment by saumoor** [comment]
Emailed info@aait.se regarding this. 
Issue needs to be fixed urgently
